### ISSUE TITLE
Fatal error while activating

### ISSUE THREAD

**Issue by dmytrodubinin** [garex/wp-testing#12]
Error when activate plugin in Wordpress 6, php 7.4
```
Warning: file_get_contents(): Filename cannot be empty in /home/bol/public_html/wp-content/plugins/wp-testing/src/Facade.php on line 386

Warning: require_once(/vendor/autoload.php): failed to open stream: No such file or directory in /home/bol/public_html/wp-content/plugins/wp-testing/src/Facade.php on line 393

Fatal error: require_once(): Failed opening required '/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/bol/public_html/wp-content/plugins/wp-testing/src/Facade.php on line 393
```

**Comment by garex** [comment]
Where have you got plugin's files? From here? They are not pre-built for install.

**Comment by dmytrodubinin** [comment]
I was try 2 ways:
1. From Releases page https://github.com/garex/wp-testing/releases
2. Download zip from repo

Put plugin directly in plugin directory because it is not available for installing from wordpress plugins repository

The problem is the same

**Comment by aitudorm** [comment]
> I was try 2 ways:
> 
>     1. From Releases page https://github.com/garex/wp-testing/releases
> 
>     2. Download zip from repo
> 
> 
> Put plugin directly in plugin directory because it is not available for installing from wordpress plugins repository
> 
> The problem is the same

Have you resolved the problem? I also has the same issue after adding plugin into `wp-content` folder. 
I am new to WordPress and right now can not even trace log files to share here

**Comment by garex** [comment]
> Where have you got plugin's files? From here? They are not pre-built for install.

**Comment by aitudorm** [comment]
> > Where have you got plugin's files? From here? They are not pre-built for install.
From your repository. Zip source

**Comment by aitudorm** [comment]
> > Where have you got plugin's files? From here? They are not pre-built for install.

From your repository. Zip source. 
Unzipped and moved to assigned folder

**Comment by aitudorm** [comment]
> > Where have you got plugin's files? From here? They are not pre-built for install.

Have you considered previous issue with logs?  I think I have the same problem, but I can't still share the logs.

**Comment by aitudorm** [comment]
And why you closed this thread as completed? @garex

**Comment by garex** [comment]
> And why you closed this thread as completed? @garex

Because ready made files was at WP repo, which closed this plugin as of anti-Russia policy. So, contact your politians.
