### ISSUE TITLE
How to get title and description by result id?

### ISSUE THREAD

**Issue by dddobriak** [garex/wp-testing#9]
Hello, help me please, how to get title and description of the result by result id which I see in the browser, like a `1qeec0bfd328a12580ba01146ed049a378`? Tnanks.
I want to modify this for the Open Graph afterwards.

**Comment by garex** [comment]
1. It's not stored in DB and calculated each time you open passing page
2. Where and why do you need it?
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пт, 14 июн. 2019 г. в 10:24, dddobriak <notifications@github.com>:

**Comment by dddobriak** [comment]
Hi, for these hooks https://www.ibenic.com/programmatically-change-yoast-seo-open-graph-meta/
I want to insert the title and image of the results in the OG's markup.
In this case, the user could share the test result in social networks.

**Comment by garex** [comment]
You should use wp testing actions/filters to get it.

I will return from vacation on sunday and will answer more detailed.

пт, 14 июня 2019 г., 18:36 dddobriak <notifications@github.com>:

**Comment by dddobriak** [comment]
ok many thanks, I will appreciate the list of hooks

**Comment by garex** [comment]
You can find them already through source code.

сб, 15 июня 2019 г., 16:24 dddobriak <notifications@github.com>:

**Comment by dddobriak** [comment]
I tried to use some hooks that I found like a wp_testing_passer_render_content and etc.., but in all cases I got an array of private properties, this did not allow me to do: (((

**Comment by garex** [comment]
Find some action where you will get passing.

For example `wp_testing_passer_get_results_before_render`.

Then call on that passing `$this->passing->buildResults()`. It will return you "collection" of `WpTesting_Model_Result`. From it you will be able to get all what you need.

**Comment by dddobriak** [comment]
many thanks
